#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --time=00:15:00
#SBATCH --error test.err     # std-error file
#SBATCH --output test.out     # std-output file
#SBATCH --account=Sis25_baroni    # account number
#SBATCH --partition=g100_usr_prod
#SBATCH --dependency=afterany:16530568

module load profile/base
module load intel/
module load intel-oneapi-mpi/
module load intel-oneapi-mkl/
module load vtune 
export PW=/g100_work/Sis25_baroni/pietrod/build_intel_741/bin/pw.x 
export D3H=/g100_work/Sis25_baroni/pietrod/build_intel_741/bin/d3hess.x 
export PH=/g100_work/Sis25_baroni/pietrod/build_intel_741/bin/ph.x
export suffix=nn${SLURM_NNODES}_${SLURM_JOB_ID}

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
srun --cpu_bind=cores $PW -i scf.in  >  scf.out_${suffix}
srun --cpu_bind=cores $D3H -i d3hess.in    >  d3hess.out_${suffix}
#srun --cpu_bind=cores $PH       -i ph_irr32.in   >  ph_irr32.out_${suffix}
#srun --cpu_bind=cores $PH   -nb 2     -i ph_irr32.in > ph_irr32_NB2.out_${suffix}
srun --cpu_bind=cores vtune -trace-mpi -collect hotspot -result-dir results_hotspot_${SLURM_JOB_ID} -- $PH -nb 2 -i ph_irr32_niter_4.in   >  ph_irr32_NB2_prof${suffix}
